#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
app_logout:
    path: /logout
app_root_default:
    path: /
    controller: App\Controller\HomeController::index
app_home:
    path: /home
    controller: App\Controller\HomeController::index